### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by aleksichen** [tim-evans/ember-plupload#27] opened 2015-07-03 10:48 UTC
I got this error message below when i install `ember-plupload` using `ember install ember-plupload`.  But i can install with the command `npm install -D  ember-plupload && ember g ember-plupload`.

```
Dyantous-MBP-2:dyantou-admin aleksichen$ ember install ember-plupload
version: 0.2.7
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/aleksichen/Documents/git/dyantou-admin/node_modules/ember-cli/lib/models/project.js:482:53
    at baseFindIndex (/Users/aleksichen/Documents/git/dyantou-admin/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /Users/aleksichen/Documents/git/dyantou-admin/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/Users/aleksichen/Documents/git/dyantou-admin/node_modules/ember-cli/lib/models/project.js:481:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/Users/aleksichen/Documents/git/dyantou-admin/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
    at Class.module.exports.Task.extend.installBlueprint (/Users/aleksichen/Documents/git/dyantou-admin/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
    at Class.<anonymous> (/Users/aleksichen/Documents/git/dyantou-admin/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/Users/aleksichen/Documents/git/dyantou-admin/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/aleksichen/Documents/git/dyantou-admin/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/aleksichen/Documents/git/dyantou-admin/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
```

**Comment by tim-evans** [comment] 2015-07-03 21:17
I can't reproduce this.

**Comment by renatocarvalho** [comment] 2017-04-30 15:08
This seems very old and there was no answer back from the author of the issue, shall we close this? :)

**Comment by tim-evans** [comment] 2017-05-01 02:34
Can do!

**Closed by tim-evans** 2017-05-01 02:34 UTC
